# Generated by Django 3.1.3 on 2021-01-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category_id', models.IntegerField()),
                ('category_name', models.CharField(max_length=250)),
                ('sub_category_id', models.IntegerField()),
                ('sub_category_name', models.CharField(max_length=250)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=80000)),
                ('price', models.CharField(max_length=255)),
                ('old_price', models.CharField(max_length=250)),
                ('file', models.CharField(max_length=250)),
                ('category_id', models.IntegerField()),
                ('category_name', models.CharField(max_length=250)),
                ('sub_category_id', models.IntegerField()),
                ('sub_category_name', models.CharField(max_length=250)),
                ('brand_id', models.IntegerField()),
                ('brand_name', models.CharField(max_length=250)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category_id', models.IntegerField()),
                ('category_name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
