# Generated by Django 3.1.3 on 2021-01-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210108_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='brand_id',
            new_name='brand',
        ),
    ]
